---
# file: roles/scripts/tasks/main.yaml
# vim:ft=ansible:

- name: "Copy common scripts to /usr/local/bin/"
  synchronize:
    src: "usr-local-bin/"
    dest: "/usr/local/bin/"
    links: "yes"
    mode: "push"
    rsync_path: "sudo rsync"
  become: no

