---
# file: roles/openssh-client/defaults/main.yaml
# vim:ft=ansible:
# https://wiki.mozilla.org/Security/Guidelines/OpenSSH

ssh_config: ssh_config.tfb.j2
ssh_known_hosts: ssh_known_hosts.tfb.j2
sshd_publickey_path: /etc/ssh/publickey

ssh_parameters:
  # https://github.com/ansible/ansible/issues/14250
  #PreferredAuthentications: "publickey,password,keyboard-interactive"
  PreferredAuthentications: "publickey,password"
  ControlMaster: "no"
  ForwardAgent: "no"
  Port: 22
  Protocol: 2
  TCPKeepAlive: "yes"
  ServerAliveInterval: 10
  ServerAliveCountMax: 6
  # sudo bash -c 'ssh-keyscan -H -t rsa,ed25519 -p 1009 bran.mlt castamere.mlt >> /etc/ssh/ssh_known_hosts'
  UserKnownHostsFile: "/etc/ssh/ssh_known_hosts"
  GlobalKnownHostsFile: "/etc/ssh/ssh_known_hosts"
  VisualHostKey: "yes"
  HashKnownHosts: "yes"
  HostKeyAlgorithms: "ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256"
  KexAlgorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp256,ecdh-sha2-nistp384,diffie-hellman-group-exchange-sha256"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  CheckHostIP: "yes"
  StrictHostKeyChecking: "yes"
  VerifyHostKeyDNS: "no"
  RSAAuthentication: "yes"
  PasswordAuthentication: "yes"
  RhostsRSAAuthentication: "no"
  HostbasedAuthentication: "no"
  GSSAPIAuthentication: "no"
  GSSAPIDelegateCredentials: "no"
  GSSAPIKeyExchange: "no"
  GSSAPITrustDNS: "no"
  Tunnel: "no"

