---
# file: nameservers.yaml
# vim:ft=ansible:

- name: ns1.tfb.net
  hosts: theon.rbsov
  tags: [ 'dns' ]
  roles:
    - role: network-interface
      network_ether_interfaces:
        - device: 'eth0:98'
          bootproto: 'static'
          address: '93.186.33.98'
          netmask: '255.255.255.224'
          gateway: '93.186.33.97'
    - role: nameserver
      nameserver_type: "master"
      nameserver_query_source: '93.186.33.98'
      tags: [ 'nameserver-role', 'ns1.tfb.net' ]

- name: ns2.tfb.net
  hosts: tyrion.rbsov
  tags: [ 'dns' ]
  roles:
    - role: network-interface
      network_ether_interfaces:
        - device: 'eth0:104'
          bootproto: 'static'
          address: '93.186.33.104'
          netmask: '255.255.255.224'
          gateway: '93.186.33.97'
    - role: nameserver
      nameserver_type: "slave"
      nameserver_query_source: '93.186.33.104'
      tags: [ 'nameserver-role', 'ns2.tfb.net' ]

- name: ns3.tfb.net
  hosts: bran.mlt
  tags: [ 'dns' ]
  roles:
    - role: network-interface
      network_ether_interfaces:
        - device: 'eth0:214'
          bootproto: 'static'
          address: '90.155.50.214'
          netmask: '255.255.255.240'
          gateway: '90.155.50.209'
        - device: 'eth0:214v6'
          netproto: 'inet6'
          bootproto: 'static'
          address: '2001:8b0:84c:717d:90:155:50:214'
          netmask: '64'
          gateway: '2001:8b0:84c:717d::1'
        - device: 'eth0:1918b'
          bootproto: 'static'
          address: '10.1.4.214'
          netmask: '255.255.255.0'
          gateway: '10.1.4.1'
    - role: nameserver
      nameserver_type: "slave"
      nameserver_query_source: '90.155.50.214'
      nameserver_query_source_v6: '2001:8b0:84c:717d:90:155:50:214'
      tags: [ 'nameserver-role', 'ns3.tfb.net' ]

- name: ns4.tfb.net
  hosts: ns4.gce
  tags: [ 'dns' ]
  roles:
    - role: nameserver
      nameserver_type: "slave"
      tags: [ 'nameserver-role', 'ns4.tfb.net' ]

- name: ns5.tfb.net
  hosts: sansa.mlt
  tags: [ 'dns' ]
  roles:
    - role: network-interface
      network_ether_interfaces:
        - device: 'eno1:222'
          bootproto: 'static'
          address: '90.155.50.222'
          netmask: '255.255.255.240'
          gateway: '90.155.50.209'
        - device: 'eno1:222v6'
          netproto: 'inet6'
          bootproto: 'static'
          address: '2001:8b0:84c:717d:90:155:50:222'
          netmask: '64'
          gateway: '2001:8b0:84c:717d::1'
        - device: 'eno1:1918b'
          bootproto: 'static'
          address: '10.1.4.222'
          netmask: '255.255.255.0'
          gateway: '10.1.4.1'
    - role: nameserver
      nameserver_type: "slave"
      nameserver_query_source: '90.155.50.222'
      nameserver_query_source_v6: '2001:8b0:84c:717d:90:155:50:222'
      tags: [ 'nameserver-role', 'ns5.tfb.net' ]

