---
#

- name: "Debian | Set some facts"
  set_fact: 
      zabbix_agent: zabbix-agent

- name: "Debian | Installing deb repository Debian"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main" 
                  state=present
  when: ansible_distribution == "Debian" and zabbix_repo == True

- name: "Debian | Installing deb-src repository Debian"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main" 
                  state=present
  when: ansible_distribution == "Debian" and zabbix_repo == True

- name: "Debian | Installing deb repository Ubuntu Lucid Lynx"
  apt_repository: repo="deb http://ppa.launchpad.net/lorenzo-milesi/zabbix24/ubuntu lucid main"
                  state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "lucid" and zabbix_repo == True

- name: "Debian | Installing deb-src repository Ubuntu Lucid Lynx"
  apt_repository: repo="deb-src http://ppa.launchpad.net/lorenzo-milesi/zabbix24/ubuntu lucid main"
                  state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "lucid" and zabbix_repo == True

- name: "Debian | Installing deb repository Ubuntu"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main" 
                  state=present
  when: 'ansible_distribution == "Ubuntu" and "{{ansible_distribution_major_version}}" >= "12" and zabbix_repo == True'

- name: "Debian | Installing deb-src repository Ubuntu"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present
  when: 'ansible_distribution == "Ubuntu" and "{{ansible_distribution_major_version}}" >= "12" and zabbix_repo == True'

- name: "Debian | Install gpp key from Ubuntu PPA keyserver"
  apt_key: keyserver=keyserver.ubuntu.com
           id=017AEECAD3635C461DD0F681526B1FF727C96182
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "lucid" and zabbix_repo == True

- name: "Debian | Install gpg key"
  apt_key: id=79EA5ED4
           url=http://repo.zabbix.com/zabbix-official-repo.key
  when: zabbix_repo == True

#- name: "Debian | Force apt-cache update"
#  apt:
#    update_cache: yes
#  when: zabbix_repo

- name: "Debian | Installing zabbix-agent"
  apt:
    pkg: "zabbix-agent"
    state: "present"
    update_cache: "yes"
    cache_valid_time: 3600

- name: "Debian | Enable the service"
  service: name={{ zabbix_agent }}
           enabled=yes

- name: "Debian | Installing python-pip"
  apt: pkg=python-pip
       state=present
       update_cache=yes
       cache_valid_time=3600
  when: zabbix_api_use == True

#- name: "Debian | Installing zabbix-piped"
#  apt: pkg=zabbix-piped
#      state=latest
#      update_cache=yes
#      cache_valid_time=3600

#- name: "Debian | Enable the zabbix-pipe service"
# service: name=zabbix-pipe
#          enabled=yes
#          state=started

