---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact: 
      zabbix_agent: zabbix-agent

- name: "RedHat | Install basic repo file"
  template: src=rhel.repo.j2
            dest=/etc/yum.repos.d/zabbix.repo
            owner=root 
            group=root 
            mode=0644
  when: zabbix_repo == True

- name: "RedHat | Installing zabbix-agent"
  yum:  pkg=zabbix-agent
        state=present

- name: "RedHat | Enable the service"
  service: name={{ zabbix_agent }}
           enabled=yes

