---
# file: roles/tw5-vxsync-automation/tasks/main.yaml
# vim:ft=ansible:

- file:
    dest: "/home/{{ ansible_env.SUDO_USER }}/bin"
    state: "directory"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0750

- copy:
    src: "tw5"
    dest: "/home/{{ ansible_env.SUDO_USER }}/bin/tw5"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0755

- lineinfile:
    dest: "/home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys"
    state: "present"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0644
    line: "{{ item }}"
  with_items:
    - 'from="81.134.152.0/26",command="/home/nicolaw/bin/tw5",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDI1IDHkmUMgZms+GO/sU2bVVtpBuZ4CkYqoJg2esX9otsmlNCdH6M4a4NisVuyEpWg7c1InPC0UR5ALUqvctMd/sce/ww8X5ILHmEo0pcST/y0h40+4xLrQXuygWLMIdd7/zd5N9kwy8vz6q6iPqW3h7cIvlTnrhK4XzHpkoRC/IVDf2AquhsJw5ZAwpmNy2pWdypoKlf+JwCjR0eKlgTL4BZlRD6wyh5nXHDd94jNjLl3D8orIIIUr5TDdE9MegHHfnThzQ8rJE6bngQB4PZeHvD+fMhijfP/166VYtYirer0VPNbW159AYPnDLOynru9kEbaEz5icXTGvKXjQW55YPA+IjO0SvzkpZ2CQaohrwQpv0TC4Zj0DGSTUBeUAJDF5/V+tG/JmAPFIX9uJw5vXVNP8K9npWFPqEKtAsdD84PXn25kw5KZk3x3xZvZMpaj12YNY7D+f7HhXj+Rc1DEa8XEDfe1ByeTm1kYUA9vJSH7gJENi6i5ckYYa2jiaHnFIbLwdfmO2rtZKxpI+cxwzbbTs4/f1gfWyqDQTF2OVXXpvzycltG5iucfpm183xCVPIOTTC62JmxlHuqaGV3am0rwLH4sz/sxF+nTTDywZJK8gxhaImW+grgfe6vxYNaoEYtE0W0VfVemBth+OC+mAxT8IcBHMX3SNeva2oVPbQ== nworthington@desk-nworthington'
    - 'from="81.134.152.0/26",command="rsync --server -logDtpre.iLs --delete . tw5.mlt.tfb.net/",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD2ck6iFPYQuhxF1Q3gMlavr7Zt+ESfiMaHUG8xWzMsD3M87T8vmpQNj76L3ygIztWioF0t2NGSW9Z6eZC8sJ8895j7lG0ZPFHeWdYjbS4r83CdePNk+3F3xlSTx2qmKqL3nX2caiEENY2/d7RkgPtaVh64mHlDF/H0AcQUN7vkPE8NVjyimJaSXd/V1xQw4AB9RBVg3Fur6EgvYr4PqKsapuIyg6+e1GNd9X9x2Men2x7HzvASyeE0hAFPAyBmB5kgDA2sJ/WHljfzd/yW+1Lp60guOxWCZB52doBxZ/RuAFs+4K6s/Xb3QP0Ad59v9oKnCVfMLcBdy6PEv0Iv87VvE5mNlwSl0ogNUYY+1xU4Bn2+eoA61PUc2nVM0K9mv8bIrk+v6qS8vuRKC6s/X9/RL9iWWW8DcinLGWk4X350YxFOrNoOm2QXCElkZmN6ziSJXVQrqF9B2+HoWRJcPqammwmZfm3E2jQZfrLS0ZhYYQvBCxyRCxNdz3QuXMRKfNw/QU/Z+7b9rrmiCxluuHLTXp6xEX9J7GTIgTGscudw9UI2wTha7CMVBDBCHhwinkBsBJ+PJn7sT4UCT7WH75GyieKJvo5NhoH55H6WX4V95HjrqI7+G38w6cHHrBEYIpDmDdyQhyzwmLE0vPeHnC53rohnojceek4wpF8ikv3NTQ== nworthington@desk-nworthington'

