---
# task file for postgresql

- name: "PostgreSQL | Create database"
  postgresql_db: name={{ server_dbname }}
                 state=present
  become_user: postgres
  when: zabbix_database_creation

- name: "PostgreSQL | Create database user"
  postgresql_user: db={{ server_dbname }}
                   name={{ server_dbuser }}
                   password={{ server_dbpassword }}
                   priv=ALL
                   state=present
  become_user: postgres
  when: zabbix_database_creation

- name: "PostgreSQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload

- name: "PostgreSQL | Importing images file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f images.sql && touch /etc/zabbix/images.done"
  args:
    creates: /etc/zabbix/images.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload

- name: "PostgreSQL | Importing data file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f data.sql && touch /etc/zabbix/data.done"
  args:
    creates: /etc/zabbix/data.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload

#- name: "PostgreSQL | Installing hot-backup script"
#  apt: pkg=postgresql-backup
#       state=present
#       update_cache=yes
#       cache_valid_time=3600
#  when: ansible_os_family == "Debian"

