---
#

- name: "Debian | Set some facts"
  set_fact: 
    datafiles_path: /usr/share/zabbix-proxy-{{ database_type }}

- name: "Debian | Installing repository Debian"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main" 
                  state=present
  when: ansible_distribution == "Debian" and zabbix_repo == True

- name: "Debian | Installing repository Debian"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main" 
                  state=present
  when: ansible_distribution == "Debian" and zabbix_repo == True

- name: "Debian | Installing repository Ubuntu"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main" 
                  state=present
  when: ansible_distribution == "ubuntu" and zabbix_repo == True

- name: "Debian | Installing repository Ubuntu"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present
  when: ansible_distribution == "ubuntu" and zabbix_repo == True

- name: "Debian | Install gpg key"
  apt_key: id=79EA5ED4
           url=http://repo.zabbix.com/zabbix-official-repo.key
  when: zabbix_repo == True

- name: "Debian | Installing zabbix-proxy-{{ database_type }}"
  apt: pkg=zabbix-proxy-{{ database_type }} 
       state=present 
       update_cache=yes
       cache_valid_time=3600

