---
# task file for mysql

- name: "MySQL | Create database"
  mysql_db: name={{ proxy_dbname }}
            state=present
  when: manage_database_creation == True

- name: "MySQL | Create database user"
  mysql_user: name={{ proxy_dbuser }}
              password={{ proxy_dbpassword }}
              priv={{ proxy_dbname }}.*:ALL 
              state=present
  when: manage_database_creation == True

- name: "MySQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && mysql -u {{ proxy_dbuser }} -p{{ proxy_dbpassword }} -D {{ proxy_dbname }} < schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  when: manage_database_sqlload == True

