---
# task file for postgresql

- name: "PostgreSQL | Create database"
  postgresql_db: name={{ proxy_dbname }}
                 state=present
  when: manage_database_creation == True

- name: "PostgreSQL | Create database user"
  postgresql_user: db={{ proxy_dbname }}
                    name={{ proxy_dbuser }}
                    password={{ proxy_dbpassword }}
                    priv=ALL
                    state=present
  when: manage_database_creation == True

- name: "PostgreSQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && psql -h localhost -U {{ proxy_dbuser }} -d {{ proxy_dbname }} -f schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  when: manage_database_sqlload == True


