---
# file: roles/mta/handlers/main.yaml
# vim:ft=ansible:

- name: reconfigure exim
  command: /usr/sbin/update-exim4.conf
  notify:
    - restart exim

- name: restart exim
  service:
    name: exim4
    state: restarted

