---
# file: roles/mta/tasks/main.yaml
# vim:ft=ansible:

# sudo debconf-get-selections | perl -na -F"\t" -e 'next unless /^exim4/; chomp for @F; print "    - { pkg: \"$F[0]\", question: \"$F[1]\", vtype: \"$F[2]\", value: \"$F[3]\" }\n";'

# TODO(2016-07-29): exim4/dc_other_hostname, exim4/mailname, exim4/dc_readhost,
#     exim4/dc_smarthost and exim4/dc_relay_nets always show up as changed no
#     matter what. Also, this is only useful for setting BEFORE the package has
#     been installed and configured. I need to replace this with the new version
#     devised by salikov which is less crack-fuelled and will actually make
#     changed AFTER package installation!

- name: "Configure MTA"
  debconf:
    name: "{{ item.pkg }}"
    question: "{{ item.question }}"
    vtype: "{{ item.vtype }}"
    value: "{{ item.value }}"
  notify:
    - reconfigure exim
  register: mta_debconf
  with_items:
    - { pkg: "exim4-config", question: "exim4/use_split_config",         vtype: "boolean", value: "true" }
    - { pkg: "exim4-config", question: "exim4/dc_localdelivery",         vtype: "select",  value: "mbox format in /var/mail/" }
    - { pkg: 'exim4-config', question: 'exim4/dc_eximconfig_configtype', vtype: 'select',  value: 'mail sent by smarthost; received via SMTP or fetchmail' }
    - { pkg: 'exim4-config', question: 'exim4/hide_mailname',            vtype: 'boolean', value: 'false' }
    - { pkg: 'exim4-config', question: 'exim4/dc_smarthost',             vtype: 'string',  value: "{{ smtp_smarthost }}" }
    - { pkg: 'exim4-config', question: 'exim4/dc_other_hostnames',       vtype: 'string',  value: "{{ ansible_fqdn }}" }
    - { pkg: 'exim4-config', question: 'exim4/mailname',                 vtype: 'string',  value: "{{ inventory_hostname_short }}.unroutable.tfb.net" }
    - { pkg: 'exim4-config', question: 'exim4/dc_readhost',              vtype: 'string',  value: "{{ ansible_fqdn }}" }
    - { pkg: "exim4-config", question: "exim4/dc_relay_nets",            vtype: "string",  value: "127.0.0.1/32 ; ::1" }
    - { pkg: "exim4-config", question: "exim4/dc_minimaldns",            vtype: "boolean", value: "false" }
    - { pkg: "exim4-config", question: "exim4/dc_postmaster",            vtype: "string",  value: "nicolaw+{{ inventory_hostname_short }}+postmaster@tfb.net" }
    - { pkg: 'postfix',      question: 'postfix/mailname',               vtype: 'string',  value: "{{ inventory_hostname_short }}.unroutable.tfb.net }}" }
    - { pkg: 'postfix',      question: 'postfix/destinations',           vtype: 'string',  value: "{{ ansible_fqdn }}" }
    - { pkg: 'postfix',      question: 'postfix/root_address',           vtype: 'string',  value: "nicolaw+{{ inventory_hostname_short }}+postfix/root_address@tfb.net" }

- name: "Install Exim4"
  apt:
    state: "latest"
    name: "{{ item }}"
  with_items:
    - exim4

- name: "Run dpkg-reconfigure for exim4-config"
  command: dpkg-reconfigure exim4-config -fnoninteractive
  when: mta_debconf.changed

- name: "Remove Postscript"
  apt:
    state: "absent"
    name: "{{ item }}"
  with_items:
    - postscript

- name: "Update MTA identity file /etc/mailname"
  template:
    src: "mailname.j2"
    dest: "/etc/mailname"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - reconfigure exim
  when: false

- name: 'Update mail alias'
  lineinfile:
    dest: '/etc/aliases'
    regexp: '^{{ item }}: '
    line: "{{ item }}: nicolaw+{{ inventory_hostname_short }}+{{ item }}@tfb.net"
    state: present
    create: yes
    owner: root
    group: root
  with_items:
    - root
    - postmaster
    - hostmaster
    - webmaster
    - abuse
    - logcheck
    - fail2ban
    - security
    - secops
    - nicolaw
  register: aliases

- name: 'Refresh mail aliases database'
  command: /usr/bin/newaliases
  when: aliases.changed

- name: "Touch Exim4 reject log"
  file:
    path: "/var/log/exim4/rejectlog"
    state: "touch"
    owner: "Debian-exim"
    group: "adm"
    mode: 0640
  changed_when: false


