---
# file: roles/antivirus/tasks/main.yaml
# vim:ft=ansible:

- apt:
    state: "latest"
    name: "{{ item }}"
  with_items:
    - rkhunter
    - chkrootkit
    - clamav-daemon

- service:
    name: '{{ item }}'
    state: 'started'
    enabled: 'yes'
  with_items:
    - clamav-freshclam
    - clamav-daemon

